/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedAppImport } from './routes/_authenticated/_app'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthenticatedAppIndexImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppSettingsIndexImport } from './routes/_authenticated/_app/settings/index'
import { Route as AuthenticatedAppHomeIndexImport } from './routes/_authenticated/_app/home/index'
import { Route as AuthenticatedAppActivityLogsIndexImport } from './routes/_authenticated/_app/activity-logs/index'
import { Route as AuthenticatedAppSettingsNotificationsIndexImport } from './routes/_authenticated/_app/settings/notifications/index'
import { Route as AuthenticatedAppSettingsDisplayIndexImport } from './routes/_authenticated/_app/settings/display/index'
import { Route as AuthenticatedAppSettingsAppearanceIndexImport } from './routes/_authenticated/_app/settings/appearance/index'
import { Route as AuthenticatedAppSettingsAccountIndexImport } from './routes/_authenticated/_app/settings/account/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAppRoute = AuthenticatedAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAppIndexRoute = AuthenticatedAppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppHomeIndexRoute = AuthenticatedAppHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppActivityLogsIndexRoute =
  AuthenticatedAppActivityLogsIndexImport.update({
    id: '/activity-logs/',
    path: '/activity-logs/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsNotificationsIndexRoute =
  AuthenticatedAppSettingsNotificationsIndexImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsDisplayIndexRoute =
  AuthenticatedAppSettingsDisplayIndexImport.update({
    id: '/settings/display/',
    path: '/settings/display/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsAppearanceIndexRoute =
  AuthenticatedAppSettingsAppearanceIndexImport.update({
    id: '/settings/appearance/',
    path: '/settings/appearance/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsAccountIndexRoute =
  AuthenticatedAppSettingsAccountIndexImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app/activity-logs/': {
      id: '/_authenticated/_app/activity-logs/'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedAppActivityLogsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/home/': {
      id: '/_authenticated/_app/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedAppHomeIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/account/': {
      id: '/_authenticated/_app/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/appearance/': {
      id: '/_authenticated/_app/settings/appearance/'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedAppSettingsAppearanceIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/display/': {
      id: '/_authenticated/_app/settings/display/'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedAppSettingsDisplayIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/notifications/': {
      id: '/_authenticated/_app/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppActivityLogsIndexRoute: typeof AuthenticatedAppActivityLogsIndexRoute
  AuthenticatedAppHomeIndexRoute: typeof AuthenticatedAppHomeIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppSettingsAccountIndexRoute: typeof AuthenticatedAppSettingsAccountIndexRoute
  AuthenticatedAppSettingsAppearanceIndexRoute: typeof AuthenticatedAppSettingsAppearanceIndexRoute
  AuthenticatedAppSettingsDisplayIndexRoute: typeof AuthenticatedAppSettingsDisplayIndexRoute
  AuthenticatedAppSettingsNotificationsIndexRoute: typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppActivityLogsIndexRoute:
    AuthenticatedAppActivityLogsIndexRoute,
  AuthenticatedAppHomeIndexRoute: AuthenticatedAppHomeIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppSettingsAccountIndexRoute:
    AuthenticatedAppSettingsAccountIndexRoute,
  AuthenticatedAppSettingsAppearanceIndexRoute:
    AuthenticatedAppSettingsAppearanceIndexRoute,
  AuthenticatedAppSettingsDisplayIndexRoute:
    AuthenticatedAppSettingsDisplayIndexRoute,
  AuthenticatedAppSettingsNotificationsIndexRoute:
    AuthenticatedAppSettingsNotificationsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedAppRouteWithChildren
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/activity-logs': typeof AuthenticatedAppActivityLogsIndexRoute
  '/home': typeof AuthenticatedAppHomeIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/settings/appearance': typeof AuthenticatedAppSettingsAppearanceIndexRoute
  '/settings/display': typeof AuthenticatedAppSettingsDisplayIndexRoute
  '/settings/notifications': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/activity-logs': typeof AuthenticatedAppActivityLogsIndexRoute
  '/home': typeof AuthenticatedAppHomeIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/settings/appearance': typeof AuthenticatedAppSettingsAppearanceIndexRoute
  '/settings/display': typeof AuthenticatedAppSettingsDisplayIndexRoute
  '/settings/notifications': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_app/activity-logs/': typeof AuthenticatedAppActivityLogsIndexRoute
  '/_authenticated/_app/home/': typeof AuthenticatedAppHomeIndexRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/settings/account/': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/_authenticated/_app/settings/appearance/': typeof AuthenticatedAppSettingsAppearanceIndexRoute
  '/_authenticated/_app/settings/display/': typeof AuthenticatedAppSettingsDisplayIndexRoute
  '/_authenticated/_app/settings/notifications/': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/activity-logs'
    | '/home'
    | '/settings'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/activity-logs'
    | '/home'
    | '/settings'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_app'
    | '/_authenticated/_app/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_app/activity-logs/'
    | '/_authenticated/_app/home/'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/settings/account/'
    | '/_authenticated/_app/settings/appearance/'
    | '/_authenticated/_app/settings/display/'
    | '/_authenticated/_app/settings/notifications/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth/login/",
        "/auth/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_app"
      ]
    },
    "/_authenticated/_app": {
      "filePath": "_authenticated/_app.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_app/",
        "/_authenticated/_app/activity-logs/",
        "/_authenticated/_app/home/",
        "/_authenticated/_app/settings/",
        "/_authenticated/_app/settings/account/",
        "/_authenticated/_app/settings/appearance/",
        "/_authenticated/_app/settings/display/",
        "/_authenticated/_app/settings/notifications/"
      ]
    },
    "/_authenticated/_app/": {
      "filePath": "_authenticated/_app/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/_authenticated/_app/activity-logs/": {
      "filePath": "_authenticated/_app/activity-logs/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/home/": {
      "filePath": "_authenticated/_app/home/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/": {
      "filePath": "_authenticated/_app/settings/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/account/": {
      "filePath": "_authenticated/_app/settings/account/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/appearance/": {
      "filePath": "_authenticated/_app/settings/appearance/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/display/": {
      "filePath": "_authenticated/_app/settings/display/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/notifications/": {
      "filePath": "_authenticated/_app/settings/notifications/index.tsx",
      "parent": "/_authenticated/_app"
    }
  }
}
ROUTE_MANIFEST_END */
